### ISSUE TITLE
You lost the game 

### ISSUE THREAD

**Issue by DoubleF3lix** [Speedy2025/dev-tag#1]
unless if the repo is still empty...

**Comment by lolgeny** [comment]
Good idea

**Comment by omorefe** [comment]
Great idea

**Comment by lolgeny** [comment]
This idea was so awesome I exploded because of how great it was

**Comment by omorefe** [comment]
same

**Comment by omorefe** [comment]
i also died of it's awesomeness

**Comment by lolgeny** [comment]
*its

**Comment by DoubleF3lix** [comment]
any further notions should be referred to cheese

**Comment by omorefe** [comment]
Noooo
